config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index' 
  resources :items, only: [:show, :edit, :new, :create]

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'step5'
      get 'step6'
      get 'done'
      get 'pay'
      post 'pay'
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/views/partial/_camera.html.haml
= link_to new_item_path do
  .purchaseBtn
    %span.purchaseBtn__text
      = "出品する"
    = image_tag "material/icon/icon_camera.png", class: "purchaseBtn__image"

app/views/partial/_footer.html.haml
%aside.appBanner
  .inner
    %h2 だれでもかんたん、人生を変えるフリマアプリ
    %p 今すぐ無料ダウンロード！
    .inner-icon
      = link_to "" do
        = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", size: "220x64"

      = link_to "" do
        = image_tag "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", size: "220x64"

%footer
  %ul.footer-nav
    %li.footer-nav-list
      %h2.footer-nav-list-title FURIMAについて
      %ul
        %li 
          = link_to "会社概要（運営会社）" 
        %li
          = link_to "プライバシーポリシー" 
        %li
          = link_to "FURIMA利用規約" 
        %li
          = link_to "ポイントに関する規約" 

    %li.footer-nav-list
      %h2.footer-nav-list-title FURIMAをみる
      %ul
        %li 
          = link_to "カテゴリー一覧" 
        %li 
          = link_to "ブランド一覧" 
      
    %li.footer-nav-list
      %h2.footer-nav-list-title ヘルプ&ガイド
      %ul
        %li 
          = link_to "FURIMAガイド" 
        %li 
          = link_to "FURIMAロゴ利用ガイドライン" 
        %li 
          = link_to "お知らせ" 

  .footer-campany
    = link_to "" do
      = image_tag "material/logo/logo-white.png", size: "220x64"
  %p © FURIMA

app/views/partial/_navbar.html.haml
%header
  .nav
    .nav-title
      .nav-title-icon
        = link_to "" do
          = image_tag "material/logo/logo.png", size: "220x60"
      .from
        = form_with local: true, class:"from-seach" do |f|
          = f.text_field :name, class: "from-seach-area", placeholder: "キーワードから探す"
          = f.submit "検索", class: "from-seach-submit"
    .nav-link
      .nav-link-choice
        = link_to "" do
          -# アイコン
          .nav-link-choice-category カテゴリから探す
        = link_to "" do
          -# アイコン
          .nav-link-choice-brand ブランドから探す
      %ul
        = link_to "" do
          %li ログイン
        = link_to "" do
          %li 新規登録