config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index' 
  resources :items, only: [:show, :edit, :new, :create]

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'step5'
      get 'step6'
      get 'done'
      get 'pay'
      post 'pay'
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
  belongs_to_active_hash :category
  belongs_to_active_hash :condition
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :delivery_days
  # belongs_to_active_hash :delivery_ways
  has_many :item_images
  # belongs_to :user
  accepts_nested_attributes_for :item_images
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.limit(10).order('created_at DESC')
  end

  def show
    @items=Item.all.includes(:item_images).order('created_at DESC')
    @url = request.url
  end

  def new
    @item = Item.new
    @item.item_images.build
  end

  def create
    @item = Item.new(item_params)
    @item.save
  end

  def edit
    # @items = Item.find(params[:id])
    # @items.save
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :price, :area_id, :category_id, :condition_id, :delivery_charge_id, :delivery_days_id, :delivery_ways_id, item_images_attributes: [:image])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
.product-footer
  .product-footer_center
    %ul
      %li 
        = link_to "プライバシーポリシー" 
      %li 
        = link_to "メルカリ利用規約" 
      %li 
        = link_to "特定商取引に関する表記" 
  .product-footer_logo
    = link_to "特定商取引に関する表記"  do
      = image_tag "material/logo/logo-white.png", size: "220x64"
  .product-footer_text
    %p @Furima

app/views/items/_header.html.haml
.items-header
  .items-header-icon
    = link_to do
      = image_tag "material/logo/logo.png", width:"200px", height:"60px"

app/views/items/_index_product.html.haml
%section.index__category
  %h2.index__category--top
    = "人気カテゴリー"
  .index__category--names
    %ul.index__category--names__box
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "レディース"
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "メンズ"
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "家電"
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "おもちゃ"

%section.index__product
  .index__product__list
    %h3.index__product__list--name
      = "アイテム一覧"
    = link_to root_path, class: "items" do
      %span
        = "もっと見る"
        = icon('fa', 'angle-right', class: 'angle')

  .product
    .product__posts
      %ul.product__posts--boxs
        - @items.each do |item|
          %li.product__posts--boxs__item
            .posts__image
              = link_to class: "product-a" do
                =image_tag item.item_images.first.image.url, class: "item-image"
                %span.posts__price
                  ￥
                  =item.price
                .posts__text
                  %p.posta__tag
                    =item.name

%section.index__category
  %h2.index__category--top
    = "人気ブランド"
  .index__category--names
    %ul.index__category--names__box
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "シャネル"
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "ナイキ"
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "アディダス"
      %li.index__category--names__boxs
        = link_to root_path, class: "category__a" do
          = "ルイ・ヴィトン"

%section.index__product
  .index__product__list
    %h3.index__product__list--name
      = "アイテム一覧"
    = link_to root_path, class: "items" do
      %span
        = "もっと見る"
        = icon('fa', 'angle-right', class: 'angle')

  .product
    .product__posts
      %ul.product__posts--boxs
        - @items.each do |item|
          %li.product__posts--boxs__item
            .posts__image
              = link_to class: "product-a" do
                =image_tag item.item_images.first.image.url, class: "item-image"
                %span.posts__price
                  ￥
                  =item.price
                .posts__text
                  %p.posta__tag
                    =item.name

app/views/items/_new_footer.html.haml
.product-footer
  .product-footer_center
    %ul
      %li 
        = link_to "プライバシーポリシー" 
      %li 
        = link_to "メルカリ利用規約" 
      %li 
        = link_to "特定商取引に関する表記" 
  .product-footer_logo
    = link_to "特定商取引に関する表記"  do
      = image_tag "material/logo/logo-white.png", size: "220x64"
  .product-footer_text
    %p @Furima

app/views/items/create.html.haml
.items__create
  = render partial: 'partial/navbar'
.create
  .create__box
    .create__box__message
      = "商品の出品が完了しました"
    = link_to root_path, class: "link" do
      = "トップページに戻る"
    = link_to items_path, class: "link" do
      = "商品詳細ページに戻る"
.items__create
  = render partial: 'partial/footer'

app/views/items/edit.html.haml
= form_with model:@item, local:true do |f|
  .wapper
    .header
      .header-icon
        = link_to do
          =image_tag "material/logo/logo.png", width:"189px", height:"49px"
    .body
      .brank
      .main_body
        .edit__main--subject
          商品の情報を入力
        .article
          .article-content
            .content-label
              .label-1
                %b 出品画像
              .label-2
                %b 必須
            .content-text
              最大10枚までアップロードできます。
            .edit_contents
              .edit_content
                .edit_content-subject1
                  .edit_content-subject1_image
                  .edit_content-subject1_function
                    .edit_content-subject1_edit
                      編集
                    .edit_content-subject1-destroy
                      削除
                .edit_content-subject2
                  .edit_content-subject2_image
                  .edit_content-subject2_function
                    .edit_content-subject2_edit
                      編集
                    .edit_content-subject2-destroy
                      削除
              .edit_content-image
                .edit_content-image_icon
                  =image_tag "material/icon/icon_camera.png", width:"24px", height:"24px"
                  = f.fields_for :item_images do |i|
                    = i.file_field :image, class: 'file-input'
                .content-image_text
                  %P ドラッグ&ドロップ 
                  またはクリックしてファイルをアップロード 
        .product_name
          .product-content
            .product-name_title
              .product-upper
                .label-1
                  %b 商品名
                .label-2
                  %b 必須
              = f.text_field :name, class: 'product-bottom'
              .product-lower
                40字以下で入力してください
            .product-bottom
              .label-1
                %b 商品の説明
              .label-2
                %b 必須
            .product-name_text
              = f.text_area :description, class: 'text-buttom', placeholder: '説明文を'
              .text-lower
        .product_explanation
          .explanation-content
            .content-1
              %b 商品の詳細
            .content-2
              .second-upper
                .upper-1
                  %b カテゴリー
                .upper-2
                  %b 必須
              .second-lower
            %input.content-3
              -# = f.select :categoly_id, Categoly.all.map { |categoly| [categoly.name,categoly.id]}
              .third-upper
              .third-lower
            .content-4
              .fourth-upper
                .upper-1
                  %b ブランド
                .upper-2
                  %b 任意
              .fourth-lower
            %input.content-5
            .content-6
              .six-upper
                .upper-1
                  %b 商品の状態
                .upper-2
                  %b 必須
            %input.content-7
        .delivery
          .delivery-content
            .delivery-1
              .upper-1
                %b 配送について
              .upper-2
            .delivery-2
              .d2-upper
                %b 配送量の負担
              .d2-lower
                %b 必須
            %input.delivery-3
            .delivery-4
              .d4-upper
                %b 発送元の地域
              .d4-lower
                %b 必須
            %input.delivery-5
            .delivery-6
              .d6-upper
                %b 発送元の地域
              .d6-lower
                %b 必須

            %input.delivery-7
        .price
          .price-content
            .price-1
              .p1-upper
                %b 価格（¥300〜9,999,999）
              .p1-lower
            .price-2
              .p2-upper
                .upper-left
                  %b 販売価格
                .upper-center
                  %b 必須
                .upper-logo
                  %b ¥
                  = f.text_field :price, class: 'upper-right'
              .p2-bottom
                .bottom-left
                  販売手数料
                .bottom-right
                  %b ¥500
              .p2-lower
                .lower-left
                  販売利益
                .lower-right
                  ¥ 4500
        .exhibition
          .exhibition-content
            = f.submit "出品する",class:"content-1"
            = f.submit "下書きに保存",class:"content-2"
            .content-3
              %a 戻る
          .exhibition-content2
            %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。


.items__new
  = render partial: 'footer'

app/views/items/index.html.haml
.items__index
  = render partial: 'partial/navbar'
%section.top
  .index__top__name
    %h2.index__top__name--title
      = "人生を変えるフリマアプリ"
    %p.index__top__name--subtitle
      FURIMAはだれでもかんたんに出品・購入できる
      %br
      フリマアプリです
    .index__top__btn
      = link_to class: "app__btn" do
        = image_tag "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "app"
      = link_to class: "goo__btn" do
        = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "goo"

%section.topReason
  %h2.topReason__title
    = "FURIMAアプリが選ばれる理由"
  %ul.topReason__lists
    %li.topReason__lists__list
      .list__pict
        %span.list__pict--num
          = "1"
        = image_tag "material/pict/pict-reason-01.jpg", class: "pict"
        %h3.list__pict__message
          %span{:style => "color: mediumturquoise;"} 3分
          %span{:style => "color: black;"} ですぐに出品！
        %p.list__pict__submessage
          = "スマホで入力するだけで簡単に出品できる！"
    %li.topReason__lists__list
      .list__pict
        %span.list__pict--num
          = "2"
        = image_tag "material/pict/pict-reason-02.jpg", class: "pict"
        %h3.list__pict__message
          %span{:style => "color: mediumturquoise;"} シンプル
          %span{:style => "color: black;"} で使いやすい！
        %p.list__pict__submessage
          = "めんどくさい入力は必要なく、検索も購入もスムーズ！"
    %li.topReason__lists__list
      .list__pict
        %span.list__pict--num
          = "3"
        = image_tag "material/pict/pict-reason-03.jpg", class: "pict"
        %h3.list__pict__message
          %span{:style => "color: mediumturquoise;"} 手数料
          %span{:style => "color: black;"} 業界最安値！
        %p.list__pict__submessage
          = "最大3%でお得に出品&購入！"

%section.indexmiddle
  .indexmiddle__name
    %h2.indexmiddle__name--title
      = "会員数日本一位"
    %p.indexmiddle__name--subtitle
      FURIMAは、フリマアプリで最も人気。
      %br
      出品・購入回数も業界最多です！
      %br
      ほしかったあの商品に出会えるかもしれません。
    .index__top__btn
      = link_to class: "app__btn" do
        = image_tag "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "app"
      = link_to class: "goo__btn" do
        = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "goo"

%section.features
  %h2.features__title
    = "FURIMAの特徴"
  .features__items
    %section.features__items__item
      %figure.features__items__image
        = image_tag "material/icon/icon-01.png", class: "features__image"
      %h3.features__items__title
        = "簡単に売り買いできる"
      %p.features__items-__text
        = "スマホひとつで、いつでもどこでも簡単に出品・購入が可能！"
    %section.features__items__item
      %figure.features__items__image
        = image_tag "material/icon/icon-03.png", class: "features__image"
      %h3.features__items__title
        = "売上金は即日振込みに対応"
      %p.features__items__text
        = "午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!"
    %section.features__items__item
      %figure.features__items__image
        = image_tag "material/icon/icon-04.png", class: "features__image"
      %h3.features__items__title
        = "様々な支払いに対応"
      %p.features__items-__text
        = "お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。"
.product-image
  = render partial: 'index_product'
.camera
  = render partial: 'partial/camera'
.items__index
  = render partial: 'partial/footer'

app/views/items/new.html.haml
= form_with model:@item, local:true do |f|
  .wapper
    .header
      .header-icon
        = link_to do
          =image_tag "material/logo/logo.png", width:"189px", height:"49px"
    .body
      .brank
      .main_body
        .article
          .article-content
            .content-label
              .label-1
                %b 出品画像
              .label-2
                %b 必須
            .content-text
              最大10枚までアップロードできます。
            .content-image
              %label.content-image_icon
                =image_tag "material/icon/icon_camera.png", width:"24px", height:"24px"
                = f.fields_for :item_images do |i|
                  = i.file_field :image, class: 'file-input'
              .content-image_text
                %P ドラッグ&ドロップ 
                またはクリックしてファイルをアップロード 
        .product_name
          .product-content
            .product-name_title
              .product-upper
                .label-1
                  %b 商品名
                .label-2
                  %b 必須
              = f.text_field :name, class: 'product-bottom'
              .product-lower
                40字以下で入力してください
            .product-bottom
              .label-1
                %b 商品の説明
              .label-2
                %b 必須
            .product-name_text
              = f.text_area :description, class: 'text-buttom', placeholder: '説明文を'
              .text-lower
        .product_explanation
          .explanation-content
            .content-1
              %b 商品の詳細
            .content-2
              .second-upper
                .upper-1
                  %b カテゴリー
                .upper-2
                  %b 必須
            = f.collection_select :category_id, Category.all, :id, :name, prompt: "--"
            .content-4
              .fourth-upper
                .upper-1
                  %b ブランド
                .upper-2
                  %b 任意
              .fourth-lower
            %input.content-5
            .content-6
              .six-upper
                .upper-1
                  %b 商品の状態
                .upper-2
                  %b 必須
            = f.collection_select :condition_id, Condition.all, :id, :value, prompt: "--" 
        .delivery
          .delivery-content
            .delivery-1
              .upper-1
                %b 配送について
              .upper-2
            .delivery-2
              .d2-upper
                %b 配送量の負担
              .d2-lower
                %b 必須
            = f.collection_select :delivery_charge_id, DeliveryCharge.all, :id, :value, prompt: "--" 
            .delivery-4
              .d4-upper
                %b 発送元の地域
              .d4-lower
                %b 必須
            = f.collection_select :area_id, Area.all, :id, :name
            .delivery-6
              .d6-upper
                %b 発送までの日数
              .d6-lower
                %b 必須
            = f.collection_select :delivery_days_id, DeliveryDays.all, :id, :value, prompt: "--"
        .price
          .price-content
            .price-1
              .p1-upper
                %b 価格（¥300〜9,999,999）
              .p1-lower
            .price-2
              .p2-upper
                .upper-left
                  %b 販売価格
                .upper-center
                  %b 必須
                .upper-logo
                  %b ¥
                  = f.text_field :price, class: 'upper-right'
              .p2-bottom
                .bottom-left
                  販売手数料
                .bottom-right
                  %b ¥500
              .p2-lower
                .lower-left
                  販売利益
                .lower-right
                  ¥ 4500
        .exhibition
          .exhibition-content
            = f.submit "出品する",class:"content-1"
            = f.submit "下書きに保存",class:"content-2"
            = link_to root_path,class: "content-3" do
              %b 戻る
          .exhibition-content2
            %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
= render partial: 'footer'

app/views/items/show.html.haml
-# .items__show
-#   = render partial: 'partial/navbar'

.show__header--contents
  .show__items--name
    %h1
      = "商品名fendi Tシャツ 美品"         
  .show__items--content
    %h2
      = "商品の説明『fendi Tシャツ 美品』は、42回の取引実績を持つじ　んさんから出品されました。フェンディ（Tシャツ/カットソー(半袖/袖なし)/レディース）の商品で、兵庫県から4~7日で発送されます。"             # = @items.text

.show__main--contents
  %img(src = "https://www.chanel.com/wfj/medias/decoupes-1534x1774-CODECOCO.jpg?context=bWFzdGVyfGNtc2ltYWdlc3w4MzYzNTR8aW1hZ2UvanBlZ3xjbXNpbWFnZXMvaGYzL2g1Yi84ODkxMzQ5MjcwNTU4LmpwZ3wyYzhlNjZmODY0NjRlMWEzZTA4MzFlMmM3YWZmNWQyMTJjZDcyOTg2YjQxNzZkMjk0ODE0YTUyZDhjNjk5ODc5" alt = "写真" class = "show_image")    
  
  .show__items--details
    %table.show_items--details__details{border:"1"}
      %tr
        %th
          = "出品者"
        %td                    
          = "出品者(current_user?)"  

      %tr
        %th
          = "カテゴリー"
        %td 
          = "レディース"

      %tr 
        %th 
          = "ブランド"
        %td 
          = "シャネル"

      %tr 
        %th 
          = "商品のサイズ"
        %td 
          = "FREE SIZE"

      %tr 
        %th 
          = "商品の状態"
        %td 
          = "未使用に近い"

      %tr 
        %th 
          = "配送料の負担"
        %td 
          = "送料込み（出品者負担)"

      %tr 
        %th 
          = "配送の方法"
        %td 
          = "未定"

      %tr 
        %th 
          = "配送元地域"
        %td 
          = "兵庫県"

      %tr 
        %th 
          = "発送日の目安"
        %td 
          = "1週間程度"

.show__price
  %span.show__price--price
    = "￥700,000" 
  %span.show__price--included
    = "(税込)"
  %span.show__price--fee
    = "送料込み"

.purchase-screen
  =link_to"購入画面に進む","#",class:"show__btn--name__link" 

%br 
%br 
%br 

                
.show__comments
  ="ほとんど着てません"
  %br
  ="タグ"
  %br
  ="タグ"
  %br
  ="タグ"

.show__link--prev__next
  .show__link--prev
    %a{href:"#"}
      %i.fa.fa-arrow-left
        エリザベス硬貨
  .show__link--next
    %a{href:"#"}
      ダイヤモンド
      %i.fa.fa-arrow-right

.show__medhia--links
  .show__medhia--links--box
    %a{href:"https://www.facebook.com/"}
      %i.fab.fa-facebook
    %a{href:"https://twitter.com/"}
      %i.fab.fa-twitter
    %a{href:"https://access.line.me/"} 
      %i.fab.fa-line
    %a{href:"https://www.pinterest.jp/"} 
      %i.fab.fa-pinterest-square
    <div class="line-it-button" data-lang="ja" data-type="share-b" data-ver="3"  data-url="request.original_url" data-color="default" data-size="small" data-count="false" style="display: none;"></div>
    <script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"></script>


.show__users
  ="jinnさんの作品"



  .show__users--other
    - @items.each do |item|
      .show__users--other__item
        =image_tag item.item_images.first.image.url, size:"220x190", class:"show__users--other__item--image"
        .show__users--other__item--contents
          .show__users--other__item--contents__name
            =item.name
          .show__users--other__item--contents__price
            =item.price      
        
          
                     
                          
.items__show
  = render partial: 'partial/footer'













    